version: "3.7"

services:
  postgres:
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    image: postgres:11
  prometheus:
    env_file:
      - .env
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    image: prom/prometheus
  grafana:
    env_file:
      - .env
    ports:
      - '3001:3000'
    volumes:
      - grafana:/var/lib/grafana
    image: grafana/grafana
  pgadmin:
    env_file:
      - .env
    ports:
      - '8002:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    image: dpage/pgadmin4:4.22
volumes:
  postgres:
  grafana:
  pgadmin:
