version: "3.7"

x-common-variables: &variables
  POSTGRES_USER: ajc-web
  POSTGRES_PASSWORD: password

services:
  ajc-back:
    container_name: ajc-back
    stdin_open: true
    tty: true
    volumes:
      - ./mnt/ajc-back:/mnt/host
    links:
      - ajc-db
    ports:
      - '9229:9229'
      - '3000:3000'
    environment:
      <<: *variables
      POSTGRES_HOST: ajc-db
      PORT: 3000
      NODE_ENV: dev
    build:
      context: C:/Users/206642150/Documents/repos/docker
      dockerfile: git/Dockerfile
      args:
        GIT_URL: https://github.com/ALJCepeda/ajc-back.git
        GIT_BRANCH: dev
  ajc-front:
    container_name: ajc-front
    volumes:
      - ./mnt/ajc-front:/mnt/host
    tty: true
    build:
      context: C:/Users/206642150/Documents/repos/docker
      dockerfile: git/Dockerfile
      args:
        GIT_URL: https://github.com/ALJCepeda/ajc-front.git
        GIT_BRANCH: dev
  ajc-db:
    container_name: ajc-db
    ports:
      - '5432:5432'
    volumes:
      - ajc-web:/var/lib/postgresql/data:Z
    environment:
      <<: *variables
    image: postgres:11
volumes:
  ajc-web:
    external: true
networks:
  default:
    attachable: true
